### ISSUE TITLE
Troubleshooting section

### ISSUE THREAD

**Issue by buzztroll** [gforghetti/dcm_python_agent_documentation#7]
We need to add a trouble shooting section where we discuss ways to solve possible problems and how to report bugs.  This would include:
- looking in the agent.conf file to verify the agent manager url and the cloud type.  
- increasing the log levels to debug
- restarting the agent
- reporting a bug with the/ opt/dcm-agent/embedded/agentve/bin/dcm-agent --report tool. This will create a tarball.  Please include this tarball with your bug report.

**Comment by gforghetti** [comment]
Done
